name: Deploy Yakuzadle  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  deploy-frontend:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4  
  
      - name: Setup Node.js  
        uses: actions/setup-node@v4  
        with:  
          node-version: '18'  
  
      - name: Install frontend dependencies  
        run: |  
          cd yakuzadle  
          npm install  
  
      - name: Build frontend  
        run: |  
          cd yakuzadle  
          npm run build  
  
      - name: Deploy to Firebase Hosting  
        uses: w9jds/firebase-action@master  
        with:  
          args: deploy --only hosting  
        env:  
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}